---
- name: Import rsyncd playbook
  ansible.builtin.import_playbook: playbooks/rsyncd.yml
  when: rsyncd | default(True)

- name: Import mirrors playbook
  ansible.builtin.import_playbook: playbooks/mirrors.yml

- name: Import caddy playbook
  ansible.builtin.import_playbook: playbooks/caddy.yml
  when: caddy | default(true)

- name: Import vsftpd playbook
  ansible.builtin.import_playbook: playbooks/vsftpd.yml
  when: vsftpd | default(true)
