---
- name: Configure a repository mirror server
  hosts: mirrors
  become: true
  roles:
    - { role: update, tags: update }
    - { role: cron, tags: cron }
    - { role: archlinux, tags: archlinux }
    - { role: debian, tags: debian }
    - { role: caddy, tags: caddy }
