---
- name: Configure a repository mirror server
  hosts: mirrors
  become: true
  roles:
    - role: robertdebock.update
      vars:
        update_reboot: false
      tags: update

    - role: archlinux
      tags: archlinux
      when: archlinux | default(True)

    - role: debian
      tags: debian
      when: debian | default(True)

    - role: ubuntu
      tags: ubuntu
      when: ubuntu | default(True)

    - role: freebsd
      tags: freebsd
      when: freebsd | default(True)

    - role: mxlinux
      tags: mxlinux
      when: mxlinux | default(True)

    - role: linuxmint
      tags: linuxmint
      when: linuxmint | default(True)

    - role: fedora
      tags: fedora
      when: fedora | default(True)

    - role: maxhoesel.caddy.caddy_server
      tags: caddy
      when: caddy | default(True)

    - role: robertdebock.cron
      vars:
        cron_jobs: "{{ common_cron_jobs | default([]) }}"
      tags: cron
      when: cron | default(True)
  tasks:
    - name: Include rsyncd tasks
      ansible.builtin.import_tasks:
        file: tasks/rsyncd.yml
      tags: rsyncd
      when: rsyncd | default(True)

    - name: Include vsftpd tasks
      ansible.builtin.import_tasks:
        file: tasks/vsftpd.yml
      tags: vsftpd
      when: vsftpd | default(True)
