---
- name: Install packages
  ansible.builtin.package:
    name: "{{ archlinux_packages }}"
    state: present

- name: Create target directory
  ansible.builtin.file:
    path: "{{ archlinux_target }}"
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0755'
    state: directory

- name: Install mirrorsync script
  ansible.builtin.template:
    src: mirrorsync.j2
    dest: "{{ archlinux_script_path }}"
    mode: '0755'

- name: Perform initial sync
  ansible.builtin.command:
    cmd: "{{ archlinux_script_path }}"
    creates: "{{ archlinux_target }}/lastsync"
  become: true
  become_user: "{{ rsync_user }}"
  when: archlinux_initial_sync

- name: Schedule cronjob
  ansible.builtin.cron:
    name: sync archlinux repo
    user: "{{ rsync_user }}"
    job: "{{ archlinux_script_path }}"
    minute: "{{ archlinux_schedule.minute }}"
    hour: "{{ archlinux_schedule.hour }}"
    day: "{{ archlinux_schedule.day }}"
    month: "{{ archlinux_schedule.month }}"
    weekday: "{{ archlinux_schedule.weekday }}"
  tags: cron

- name: Expose mirror to Caddy
  ansible.builtin.include_role:
    name: caddy
    tasks_from: fileserver
  vars:
    caddy_fileserver_vhost: "{{ archlinux_vhost }}"
    caddy_fileserver_root: "{{ archlinux_target }}"
    caddy_fileserver_marker: "archlinux"
  tags: caddy
