---
- name: Set facts
  ansible.builtin.set_fact:
    mirrorsync_sanitized_name: "{{ mirrorsync_name | replace('_', '-') }}"

- name: Set mirrorsync definition
  ansible.builtin.set_fact:
    mirrorsync_definition:
      packages: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_packages', default=['bash', 'curl', 'rsync']) }}"
      script: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_script', default='/usr/bin/mirrorsync-' + mirrorsync_sanitized_name) }}"
      target: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_target', default=rsync_root + '/' + mirrorsync_sanitized_name) }}"
      lock: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_lock', default='/tmp/mirrorsync-' + mirrorsync_sanitized_name + '.lck') }}"
      source_url: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_source_url') }}"
      lastupdate_url: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_lastupdate_url', default='') }}"
      lastupdate_file: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_lastupdate_file', default='') }}"
      logdir: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_logdir', default='/var/log/' + mirrorsync_sanitized_name) }}"
      logfile: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_logfile', default='mirrorsync.log') }}"
      logcycle: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_logcycle', default=7) }}"
      timeout: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_timeout', default=600) }}"
      contimeout: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_contimeout', default=60) }}"
      rsync_options: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_rsync_options', default=[]) }}"
      prescript: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_prescript', default='') }}"
      postscript: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_postscript', default='') }}"
      schedule: "{{ lookup('ansible.builtin.vars', mirrorsync_name + '_schedule', default='') }}"

- name: Output mirrorsync definition
  ansible.builtin.debug:
    var: mirrorsync_definition

- name: Install packages
  ansible.builtin.package:
    name: "{{ mirrorsync_definition.packages }}"
    state: present

- name: Create target directory
  ansible.builtin.file:
    path: "{{ mirrorsync_definition.target }}"
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0755'
    state: directory

- name: Create log directory
  ansible.builtin.file:
    path: "{{ mirrorsync_definition.logdir }}"
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0755'
    state: directory

- name: Template mirrorsync script
  ansible.builtin.template:
    src: mirrorsync.j2
    dest: "{{ mirrorsync_definition.script }}"
    mode: '0755'

- name: Import cronjob role
  ansible.builtin.import_role:
    name: cron
    tasks_from: job
  vars:
    cron_job_name: "{{ mirrorsync_sanitized_name }}"
    cron_job_user: "{{ rsync_user }}"
    cron_job_command: "{{ mirrorsync_definition.script }}"
    cron_job_expression: "{{ mirrorsync_definition.schedule }}"
  tags: cron
