---
- name: Install required packages for Debian
  ansible.builtin.apt:
    name: "{{ caddy_debian_packages }}"
    state: present
    update_cache: true

- name: Add Caddy GPG key
  ansible.builtin.apt_key:
    url: "{{ caddy_debian_key_url }}"
    keyring: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    state: present

- name: Add Caddy repository
  ansible.builtin.uri:
    url: "{{ caddy_debian_sources_url }}"
    dest: /etc/apt/sources.list.d/caddy-stable.list
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
