---
- name: Create a vhost in Caddyfile
  ansible.builtin.blockinfile:
    path: "{{ caddy_config_file }}"
    content: |
      {{ caddy_fileserver_vhost }} {
          log
          root * {{ caddy_fileserver_root }}
          file_server browse
      }
    prepend_newline: true
    append_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ caddy_fileserver_marker }}"
    validate: "{{ caddy_validation_command }}"
    state: present
  notify: restart caddy
