---
- name: Include distribution-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Enable and start caddy
  ansible.builtin.service:
    name: caddy
    enabled: true
    state: started

- name: Stat log file
  ansible.builtin.stat:
    path: "{{ caddy_log_file }}"
  register: caddy_access_log

- name: Create log file
  ansible.builtin.file:
    path: "{{ caddy_log_file }}"
    state: touch
    owner: caddy
    group: caddy
    mode: '0644'
  when: not caddy_access_log.stat.exists

- name: Stat Caddyfile
  ansible.builtin.stat:
    path: /etc/caddy/Caddyfile
  register: caddy_config_file

- name: Template Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    validate: caddy validate --config %s --adapter caddyfile
    mode: '0644'
  notify: restart caddy
  when: not caddy_config_file.stat.exists
