---
- name: Enable Caddy Copr repository
  community.general.copr:
    name: "{{ caddy_redhat_copr_name }}"
    state: enabled

- name: Install Caddy
  ansible.builtin.dnf:
    name: caddy
    state: present
