- name: Import infOpen.rsync-server role
  ansible.builtin.import_role:
    name: infOpen.rsync-server
  vars:
    rsync_server_group:
      name: "{{ common_rsync_group | default('rsync') }}"
    rsync_server_user:
      name: "{{ common_rsync_user | default('rsync') }}"
    rsync_default_global_config: |-
      uid = 65534
      gid = 65534
      log file = /var/log/rsync/rsyncd.log
    rsync_server_config_main:
      global: "{{ rsync_global_config | default(rsync_default_global_config) }}"
      modules: "{{ common_rsync_modules | default([]) }}"

- name: Enable and start rsyncd
  ansible.builtin.service:
    name: "{{ rsync_server_service.name }}" # from role
    enabled: true
    state: started
