---
- name: "Clone archvsync repository : archive"
  ansible.builtin.git:
    repo: "{{ debian_archive_repo_git }}"
    version: "{{ debian_archive_repo_version }}"
    dest: "{{ debian_archive_repo_path }}"

- name: "Create target directory : archive"
  ansible.builtin.file:
    path: "{{ debian_archive_to }}"
    owner: "{{ common_rsync_user }}"
    group: "{{ common_rsync_user }}"
    mode: '0755'
    state: directory

- name: "Create log directory : archive"
  ansible.builtin.file:
    path: "{{ debian_archive_logdir }}"
    owner: "{{ common_rsync_user }}"
    group: "{{ common_rsync_user }}"
    mode: '0755'
    state: directory

- name: "Template ftpsync.conf : archive"
  ansible.builtin.template:
    src: ftpsync.conf.j2
    dest: "{{ debian_archive_repo_path }}/etc/ftpsync.conf"
    mode: '0644'

- name: Finalize mirror
  ansible.builtin.include_role:
    name: common
    tasks_from: mirror
  vars:
    common_mirror_name: debian-archive
    common_mirror_rsync_path: "{{ debian_archive_to }}"
    common_mirror_rsync_comment: "{{ debian_archive_comment }}"
    common_mirror_cron_expression: "{{ debian_archive_schedule }}"
    common_mirror_cron_script: "{{ debian_archive_job }}"
