---
cron_package_debian: cron
cron_service_debian: cron
cron_package_redhat: cronie
cron_service_redhat: crond

cron_package: "{{ lookup('ansible.builtin.vars', 'cron_package_' + ansible_os_family | lower) }}"
cron_service: "{{ lookup('ansible.builtin.vars', 'cron_service_' + ansible_os_family | lower) }}"
