---
- name: Set default expression
  ansible.builtin.set_fact:
    cron_job_expression: "{{ cron_job_dummy_expression }}"
  when:
    - cron_job_expression is not defined
      or cron_job_expression is not string
      or not cron_job_expression

- name: Split expression string
  ansible.builtin.set_fact:
    cron_job_schedule: "{{ cron_job_expression | ansible.builtin.split }}"

- name: Schedule cronjob
  ansible.builtin.cron:
    name: "{{ cron_job_name }}"
    user: "{{ cron_job_user }}"
    job: "{{ cron_job_command }}"
    minute: "{{ cron_job_schedule[0] }}"
    hour: "{{ cron_job_schedule[1] }}"
    day: "{{ cron_job_schedule[2] }}"
    month: "{{ cron_job_schedule[3] }}"
    weekday: "{{ cron_job_schedule[4] }}"
