---
- name: Install cron
  ansible.builtin.package:
    name: "{{ cron_package }}"
    state: present

- name: Enable and start cron
  ansible.builtin.service:
    name: "{{ cron_service }}"
    enabled: true
    state: started
