---
- name: Clone archvsync repository
  ansible.builtin.git:
    repo: "{{ debian_archive_repo_git }}"
    version: "{{ debian_archive_repo_version }}"
    dest: "{{ debian_archive_repo_path }}"

- name: Create target directory
  ansible.builtin.file:
    path: "{{ debian_archive_to }}"
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0755'
    state: directory

- name: Create log directory
  ansible.builtin.file:
    path: "{{ debian_archive_logdir }}"
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0755'
    state: directory

- name: Template ftpsync.conf
  ansible.builtin.template:
    src: ftpsync.conf.j2
    dest: "{{ debian_archive_repo_path }}/etc/ftpsync.conf"
    mode: '0644'

- name: Import cronjob role
  ansible.builtin.import_role:
    name: cron
    tasks_from: job
  vars:
    cron_job_name: debian-archive
    cron_job_user: "{{ rsync_user }}"
    cron_job_command: "{{ debian_archive_repo_path }}/bin/ftpsync-cron"
    cron_job_expression: "{{ debian_archive_schedule | default('') }}"
  tags: cron
