---
- name: Assert variables
  ansible.builtin.assert:
    that:
      - rsyncd_name is defined
      - rsyncd_path is defined
      - rsyncd_comment is defined

- name: "Register rsyncd module : {{ rsyncd_name }}"
  ansible.builtin.set_fact:
    rsyncd_modules: "{{ rsyncd_modules + [{'name': rsyncd_name, 'path': rsyncd_path, 'comment': rsyncd_comment}] }}"
