---
- name: Set facts
  ansible.builtin.set_fact:
    ubumirror_dir: "{{ lookup('ansible.builtin.vars', 'ubuntu_' + ubumirror + '_dir') }}"
    ubumirror_script: "{{ ubuntu_repo_path }}/ubu{{ ubumirror }}"
    ubumirror_schedule: "{{ lookup('ansible.builtin.vars', 'ubuntu_' + ubumirror + '_schedule') }}"

- name: Output facts
  ansible.builtin.debug:
    msg:
      - "name: {{ ubumirror }}"
      - "dir: {{ ubumirror_dir }}"
      - "schedule: {{ ubumirror_schedule }}"

- name: Create dir
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.vars', 'ubuntu_' + ubumirror + '_dir') }}"
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0755'
    state: directory

- name: Schedule cronjob
  ansible.builtin.cron:
    name: "sync ubuntu {{ ubumirror }} repo"
    user: "{{ rsync_user }}"
    job: "{{ ubumirror_script }}"
    minute: "{{ ubumirror_schedule.minute }}"
    hour: "{{ ubumirror_schedule.hour }}"
    day: "{{ ubumirror_schedule.day }}"
    month: "{{ ubumirror_schedule.month }}"
    weekday: "{{ ubumirror_schedule.weekday }}"
  tags: cron
