---
- name: "Set facts : {{ ubumirror }}"
  ansible.builtin.set_fact:
    ubuntu_definition:
      dir: "{{ lookup('ansible.builtin.vars', 'ubuntu_' + ubumirror + '_dir') }}"
      script: "{{ ubuntu_repo_path }}/ubu{{ ubumirror }}"
      schedule: "{{ lookup('ansible.builtin.vars', 'ubuntu_' + ubumirror + '_schedule', default=common_cron_expression) }}"
      comment: "{{ lookup('ansible.builtin.vars', 'ubuntu_' + ubumirror + '_comment') }}"

- name: "Output ubumirror definition : {{ ubumirror }}"
  ansible.builtin.debug:
    var: ubuntu_definition

- name: "Create dir : {{ ubumirror }}"
  ansible.builtin.file:
    path: "{{ ubuntu_definition.dir }}"
    owner: "{{ common_rsync_user }}"
    group: "{{ common_rsync_user }}"
    mode: '0755'
    state: directory

- name: Finalize mirror
  ansible.builtin.include_role:
    name: common
    tasks_from: mirror
  vars:
    common_mirror_name: "ubuntu-{{ ubumirror }}"
    common_mirror_rsync_name: "{{ 'ubuntu-' + ubumirror if ubumirror != 'archive' else 'ubuntu' }}"
    common_mirror_rsync_path: "{{ ubuntu_definition.dir }}"
    common_mirror_rsync_comment: "{{ ubuntu_definition.comment }}"
    common_mirror_cron_expression: "{{ ubuntu_definition.schedule }}"
    common_mirror_cron_script: "{{ ubuntu_definition.script }}"
