---
- name: Create rsync user
  ansible.builtin.user:
    name: "{{ common_rsync_user }}"
    shell: /usr/sbin/nologin
    system: true
    password_lock: true
    create_home: true
    home: "{{ common_rsync_root }}"

- name: Create vsftpd user
  ansible.builtin.user:
    name: "{{ common_vsftpd_user }}"
    shell: /usr/sbin/nologin
    system: true
    password_lock: true
    create_home: true
    home: "{{ common_vsftpd_root }}"

# debian lxc does not have sudo installed by default
# required for sudoers support in robertdebock.users
- name: Ensure sudo is installed
  ansible.builtin.package:
    name: sudo
    state: present

# prevents lxc from hanging on
# "maxhoesel.caddy.caddy_server : Caddy is installed"
- name: Disable and mask systemd-networkd-wait-online
  ansible.builtin.systemd:
    name: systemd-networkd-wait-online.service
    enabled: false
    state: stopped
    masked: true
  when: ansible_virtualization_type == 'lxc'
