---
- name: Add system users if not in common_users
  ansible.builtin.set_fact:
    common_users: "{{ common_users + [common_rsync_default_user] }}"
  when: (common_users | selectattr('name', 'match', item) | list | length) == 0
  loop:
    - "{{ common_rsync_user }}"
    - "{{ common_vsftpd_user }}"
