---
- name: Create rsync user
  ansible.builtin.user:
    name: "{{ common_rsync_user }}"
    shell: /usr/sbin/nologin
    system: true
    password_lock: true
    create_home: true
    home: "{{ common_rsync_root }}"

- name: Create vsftpd user
  ansible.builtin.user:
    name: "{{ common_vsftpd_user }}"
    shell: /usr/sbin/nologin
    system: true
    password_lock: true
    create_home: true
    home: "{{ common_vsftpd_root }}"
