---
- name: Add system users if not in common_users
  ansible.builtin.set_fact:
    common_users: "{{ common_users + [common_rsync_default_user] }}"
  when: (common_users | selectattr('name', 'match', item) | list | length) == 0
  loop:
    - "{{ common_rsync_user }}"
    - "{{ common_vsftpd_user }}"

# debian lxc does not have sudo installed by default
# required for sudoers support in robertdebock.users
- name: Ensure sudo is installed
  ansible.builtin.package:
    name: sudo
    state: present

# prevents lxc from hanging on
# "maxhoesel.caddy.caddy_server : Caddy is installed"
- name: Disable and mask systemd-networkd-wait-online
  ansible.builtin.systemd:
    name: systemd-networkd-wait-online.service
    enabled: false
    state: stopped
    masked: true
