---
- name: Assert required vars
  ansible.builtin.assert:
    that: item | default('', true) | trim != ''
    quiet: true
  loop:
    - common_mirror_name
    - common_mirror_rsync_path
    - common_mirror_rsync_comment
    - common_mirror_cron_expression
    - common_mirror_cron_script

- name: "Configure rsyncd : {{ common_mirror_name }}"
  tags: rsync
  when: rsync | default(True)
  block:
    - name: "Set rsync module fact : {{ common_mirror_name }}"
      ansible.builtin.set_fact:
        common_mirror_rsync_module:
          name: "{{ common_mirror_rsync_name | default(common_mirror_name) }}"
          config: |
            path = {{ common_mirror_rsync_path }}
            comment = {{ common_mirror_rsync_comment }}
            read only = yes
            list = yes

    - name: "Append to common_rsync_modules : {{ common_mirror_name }}"
      ansible.builtin.set_fact:
        common_rsync_modules: "{{ common_rsync_modules + [common_mirror_rsync_module] }}"

- name: "Configure crontab : {{ common_mirror_name }}"
  tags: cron
  block:
    - name: "Split cron expression : {{ common_mirror_name }}"
      ansible.builtin.set_fact:
        common_mirror_cron_schedule: "{{ common_mirror_cron_expression | ansible.builtin.split }}"

    - name: "Set cron job fact : {{ common_mirror_name }}"
      ansible.builtin.set_fact:
        common_mirror_cron_job:
          name: "{{ common_mirror_name }}"
          minute: "{{ common_mirror_cron_schedule[0] }}"
          hour: "{{ common_mirror_cron_schedule[1] }}"
          day: "{{ common_mirror_cron_schedule[2] }}"
          month: "{{ common_mirror_cron_schedule[3] }}"
          weekday: "{{ common_mirror_cron_schedule[4] }}"
          job: "{{ common_mirror_cron_script }}"
          user: "{{ common_rsync_user }}"
          state: present

    - name: "Append to common_cron_jobs : {{ common_mirror_name }}"
      ansible.builtin.set_fact:
        common_cron_jobs: "{{ common_cron_jobs + [common_mirror_cron_job] }}"
