---
archlinux_lock: /tmp/sync-archlinux.lck
archlinux_initial_sync: false
archlinux_save_lastsync: true
archlinux_delay_updates: true
archlinux_verbose: false
archlinux_vhost: "{{ caddy_localhost }}"
