---
- name: Install rsync
  ansible.builtin.package:
    name: rsync
    state: present

- name: Create rsync group
  ansible.builtin.group:
    name: rsync
    gid: "{{ rsync_uid }}"
    system: true
    state: present

- name: Create rsync user
  ansible.builtin.user:
    name: "{{ rsync_user }}"
    uid: "{{ rsync_uid }}"
    group: rsync
    home: /var/lib/rsync
    shell: /sbin/nologin
    system: true
    state: present

- name: Create root directory
  ansible.builtin.file:
    path: "{{ rsync_root }}"
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0755'
    state: directory

- name: Enable and start rsyncd
  ansible.builtin.service:
    name: rsync
    enabled: true
    state: started

- name: Create log file
  ansible.builtin.file:
    path: "{{ rsync_log_file }}"
    state: touch
    mode: '0644'

- name: Create motd file
  ansible.builtin.copy:
    content: "{{ rsync_motd_content }}"
    dest: "{{ rsync_motd_file }}"
    mode: '0644'

- name: Template rsyncd.conf
  ansible.builtin.template:
    src: "{{ rsync_config_src }}"
    dest: /etc/rsyncd.conf
    mode: '0644'
  notify: restart rsyncd
