name: CI

on:
  pull_request:
    paths:
      - "**.ya?ml"
      - "!*.example.ya?ml"
      - ".ansible-lint.ya?ml"
      - ansible.cfg
  push:
    paths:
      - "**.ya?ml"
      - "!*.example.ya?ml"
      - ".ansible-lint.ya?ml"
      - ansible.cfg
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - name: almalinux
            version: "10"
          - name: debian
            version: "13"
      fail-fast: false
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Install molecule
        run: uv tool install --with-executables-from ansible-core --with 'molecule-plugins[docker]' molecule

      - name: Run molecule
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO_NAME: ${{ matrix.distro.name }}
          MOLECULE_DISTRO_VERSION: ${{ matrix.distro.version }}
